name: gitleaks

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'  
    - name: gitleaks-action checkout(private)
      uses: actions/checkout@v2
      with:
        repository: fundingasiagroup/gitleaks-action
        token: ${{ secrets.GIT_ACTION_TOKEN }} # stored in GitHub secrets
        path: ./naction  
    - name: run git actions
      uses: ./naction
